keep-starknet-strange/madara

pallets/cairo/src/compilation/mock.rs, pallets/cairo/src/execution/cairo_vm_executor.rs, pallets/cairo/src/execution/samples/add.json, pallets/cairo/src/lib.rs, pallets/cairo/src/types.rs
Currently only hardcoded program is run when call execute cairo assembly extrinsic.
Issue Number: fixes #15
It is now possible to run deployed cairo assembly programs.
=> Execute deployed cairo assembly programs instead of hardcoded ones

.github/workflows/check.yml
Issue Number: #67 
- Adding `nextest` to the CI workflow
- Replacing the call of `cargo test` with `cargo nextest run`
It seems there's an improvement of about 2s when running tests with `cargo nextest run` instead of running `cargo test`
`cargo test  3.17s user 1.49s system 78% cpu 5.915 total`
`cargo nextest run  1.20s user 0.65s system 91% cpu 2.021 total`
CI output now shows the following:
=> add nextest to CI workflow

.github/workflows/test.yml
Use `cargo tarpaulin` `--skip-clean` flag to use the cached dependencies from `Swatinem/rust-cache@v2` in coverage ci
`cargo tarpaulin --workspace` defaults to clean the directory
https://github.com/keep-starknet-strange/madara/actions/runs/4556469374/jobs/8036859662#step:6:12
- tarpaulin uses cache
=> feat(ci): no clean coverage dependencies

.github/workflows/docker.yml
only build on release
build on merge to main, but takes 1hr
build on release tag
=> ci: build docker on release

crates/pallets/starknet/src/message.rs, crates/pallets/starknet/src/tests.rs, crates/primitives/starknet/src/transaction/mod.rs, crates/primitives/starknet/src/transaction/types.rs, crates/primitives/starknet/tests/crypto.rs, crates/primitives/starknet/tests/transaction.rs
The current `execute` method doesn't check if the transaction version being passed is valid or not.
`Transaction.version` uses a `U256` as the type.
Issue Number: #127 
This PR adds a transaction version validation similar to what happens in the [blockifier](https://github.com/tdelabro/blockifier/blob/no_std-support/crates/blockifier/src/transaction/account_transaction.rs#L100).
It also replaces the usage of `U256` for the version type in the `Transaction` struct to be an `u8`, as specified in the issue.
Existing tests were updated, and new ones were added.
=> Verify tx version on execute

Cargo.lock, Cargo.toml, crates/client/mapping-sync/Cargo.toml, crates/client/mapping-sync/src/sync_blocks.rs, crates/client/rpc-core/Cargo.toml, crates/client/rpc-core/src/lib.rs, crates/client/rpc-core/src/tests.rs, crates/client/rpc/Cargo.toml, crates/pallets/starknet/src/lib.rs, crates/primitives/digest-log/Cargo.toml, crates/primitives/digest-log/src/error.rs, crates/primitives/digest-log/src/lib.rs, crates/primitives/digest-log/src/tests.rs
Only the starknet block hash was present in the substrate block digest
- the whole starknet block is now pushed into the substrate block digest
- the `block_tag` variant of the `BlockId` rpc symbol is now serialized in snake_case
=> Push whole block to digest

tests/package-lock.json, tests/package.json
The `package.json` for the tests doesn't specify any required version for node. However, with node 16 the "latest" version tag was not supported
Add `engine: node >= 18` in package.json
=> Add node version in package.json

Cargo.lock, Cargo.toml
Installs `starknet-rs` crates from GitHub.
Installs `starknet-rs` crates from crates.io instead.
Because it's generally a better practice to install from crates.io :)
=> chore: use starknet-rs from crates.io

.github/ISSUE_TEMPLATE/02_FEATURE_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md
The feature request template and the pull request template use checkboxes (`[ ]`) to help the dev choose in between several categories of issues/update, etc.
However, the `[ ]` is interpreted by GitHub as a task list and GitHub consequently considers that issues and PR have partial tasks execution.
Updated the comments to make the dev choose differently.
No
I have also renamed "Issue number" into "Resolves" as this is a special keywords used by github to link issues and PR
=> Remove checkboxes from issue and PR template

crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/primitives/starknet/src/transaction/mod.rs, crates/primitives/starknet/src/transaction/types.rs
This PR adds the block Hash and Number to `TransactionReceiptWrapper`.
The `TransactionReceiptWrapper` Struct doesn't have the Block Number and Hash.
Resolves: #252 
`TransactionReceiptWrapper` now has these new fields.
Tests were also updated.
No
=> Add Block Hash and Number to TransactionReceiptWrapper

infra/docker/Dockerfile.dev
The docker instance currently doesn't have the capability of running npm scripts since Node.js and npm aren't installed. This PR fixes that by adding a line to install them and removing a line which erases the bin directories.
- Bugfix
Docker instance isn't able to run npm scripts
Resolves: #285 
Added missing step to install Node.js and npm in the container, which are required to run `npm run test-seq`.
I'm 100% sure about this other change but I eliminated the lines which removes /usr/bin and /usr/sbin since it's affecting the ability to run Node.js and npm inside the container.
Another alternative could be creating a separate container to run the npm scripts, this way we could avoid removing the line. Let me …
=> bug: docker instance not able to run npm scripts fix

infra/starknet-stack/docker-compose.yaml, infra/starknet-stack/docker-compose.yml
- Other (please describe): infra, the closest conventional-commit tag is build IMO
Every piece of the starknet stack (madara, madara-app, etc...) needs to be run on its own.
Resolves: #412 
A new docker-compose.yml allows to start the services composing the starknet stack. This file serves as a foundation for adding later services. Current services are
- madara
- madara-app
No
This configuration targets local setup and tries to maximize ease of use. As such : 
- madara is opened as much as possible (prometheus, rpc and websocket are exposed on the host)
- madara-app is exposed on port 8080 (to avoid conflicts with local HTTP servers)
=> build: add a docker compose for the starknet stack

crates/client/rpc-core/src/lib.rs, crates/client/rpc/src/lib.rs
- Feature
When a contributor implements a route, they need to figure out what are the input and output of this route,
then edit both the `trait` and the `impl`.
The `trait` is complete and the contributor only needs to implement it, this resolving the issue of checking
in some other repo/sources what are its parameters.
No
I have not fixed the wrong `Transaction` currently used in the `get_transaction_by_block_by_index` as this was
out of the scope of this PR (and @greged93 is working on this rn).
=> Write the whole RPC trait and put not implemented in the impl

docs/contributor-starter-pack.md
@tdelabro sent me [this repo](https://github.com/rusty-crewmates/substrate-tutorials) for substrate tutorials some days ago. I've been finding them helpful in understanding some Substrate details, which I had read in the docs. 
More people probably know about them, but they should be a reference in the contributor starter pack.
No
=> Add Substrate tutorials to the Starter pack Docs

crates/client/mapping-sync/src/lib.rs, crates/client/mapping-sync/src/sync_blocks.rs, crates/client/rpc/src/lib.rs, crates/node/src/rpc/mod.rs, crates/node/src/service.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/runtime_api.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/primitives/starknet/src/block/header.rs, crates/primitives/starknet/src/crypto/commitment/mod.rs, crates/primitives/starknet/src/crypto/hash/mod.rs, crates/primitives/starknet/src/crypto/hash/pedersen.rs, crates/primitives/starknet/src/crypto/hash/poseidon.rs, crates/primitives/starknet/src/crypto/merkle_patricia_tree/merkle_node.rs, crates/primitives/starknet/src/crypto/merkle_patricia_tree/merkle_tree.rs, crates/primitives/starknet/src/tests/crypto.rs, crates/primitives/starknet/src/traits/hash.rs, crates/primitives/starknet/src/traits/mod.rs, crates/runtime/src/lib.rs
Client uses default Pedersen hasher in order to compute block header hash. PR updates the runtime API in order to provide a way to retrieve the hasher used by the runtime.
- Feature
Resolves: #402 
- Adds runtime API endpoint in order for the client to retrieve runtime hasher.
No
Please note that I was not able to update the Pedersen hasher to a generic type hasher in one file for the functions relating to [transaction hash calculation](https://github.com/keep-starknet-strange/madara/blob/main/crates/primitives/starknet/src/crypto/commitment/mod.rs#L138), this being due to the fact that these functions are currently used in [From implementations](https://github.com/keep-starknet-strange/madara/blob/main/crates/primitives/starknet/src/transaction/types.rs#L309).
=> feat: get runtime hasher into client

crates/primitives/starknet/src/execution/felt252_wrapper.rs
Revert the macro introduced which implemented From and TryFrom for Felt252Wrapper, only keeping the implementations for u64 and u128, thus applying KISS and YAGNI.
Macro was added to Felt252Wrapper and introduces unneeded implementations for conversion between Felt252Wrapper and other built-in types (u8, u16, u32, u64).
Resolves: #NA
Remove the macro to simplify the code and keep only the needed implementation (u64 and u128).
- Cleaning unneeded impls
No
Done to follow the Keep It Simple Stupid (KISS) and the You Aren't Gonna Need It (YAGNI) principles.
=> fix: clean the macros and unused code

Cargo.toml, crates/client/rpc-core/src/utils.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/message.rs, crates/pallets/starknet/src/tests/call_contract.rs, crates/pallets/starknet/src/tests/declare_tx.rs, crates/pallets/starknet/src/tests/deploy_account_tx.rs, crates/pallets/starknet/src/tests/erc20.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/primitives/starknet/src/crypto/commitment/mod.rs, crates/primitives/starknet/src/execution/felt252_wrapper.rs, crates/primitives/starknet/src/starknet_serde/mod.rs, crates/primitives/starknet/src/tests/crypto.rs, crates/primitives/starknet/src/tests/transaction.rs, crates/primitives/starknet/src/transaction/mod.rs, crates/primitives/starknet/src/transaction/types.rs, tests/util/starknet.ts, tests/util/utils.ts
- Feature
The current transaction types use `U256` for `nonce` and `max_fees`.
Resolves: #456 
This PR makes the type of `nonce` and `max_fees` -> `Felt252Wrapper`.
=> feat: add `Felt252Wrapper` for `nonce` and `max_fees`

docs/getting-started.md, infra/docker/docker_run.sh
This PR introduces some corrections to the `docker_run.sh` file and the documentation. It also tries to clarify the usage of the script.
Bug
- Bugfix
- It was not possible to run the `infra/docker/docker_run.sh` due to permissions
- The `infra/docker/docker_run.sh` would fail to run if we were not in the right folder
- The `Getting Started` documentation had wrong paths for running some commands
- The `Getting Started` documentation was unclear on running the `docker_run.sh`. From the text, it seemed that you should change the content of the `docker-compose.yml`, replacing the content of the command. In reality, the `docker_run.sh` is a wrapper for the `docker-compose.yml` and …
=> bug: Corrections on docker_run.sh and the documentation relative to it

tests/tests/test-rpc/test-starknet-rpc.ts, tests/util/setup-dev-tests.ts
All the tests are in the same describe, hindering readability of input file and output results.
Added a `describe` per route (SUT) and rephrased the `it` to be descriptive of what's being actually tested.
No
We could add test scaffolding for not implemented routes as well, with "describe.skip" and ask the contributor to "unskip and make pass".
See <img width="489" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/18620296/0b106866-c46a-47a6-8588-602fd183a933"> compared to <img width="492" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/18620296/d77df974-8dc5-49ee-8b3d-fbf545b58a21">.
I didn't remove tests, so not …
=> Add describe for route in rpc tests

.github/workflows/benchmark.yml
- Feature
Benchmarks are run against the main branch but historical data is not available.
Resolves: #488
TPS and Extrinsic/block metrics are visible at [keep-starknet-strange.github.io/madara/dev/bench](https://keep-starknet-strange.github.io/madara/dev/bench)
No
=> Update madara gh page with benchmark graphs

.github/workflows/benchmark.yml, Cargo.lock, Cargo.toml, crates/client/db/Cargo.toml, crates/node/Cargo.toml, crates/node/src/service.rs, crates/node/src/starknet.rs, crates/runtime/src/pallets.rs, infra/local-testnet/run.sh, tests/util/dev-node.ts, tests/util/setup-dev-tests.ts
Upgrade substrate version to polkadot-v0.9.43.
Co-authored-by: @abdelhamidbakhta
=> ⬆️ upgrade substrate to polkadot-v0.9.43

.github/workflows/benchmark.yml
- Bugfix
The Benchmarking CI fails, most probably because of a permission issue, see
- [this failing run](https://github.com/keep-starknet-strange/madara/actions/runs/5132996057/jobs/9235548571?pr=501)
- [this SO thread](https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac)
Added the `pull-requests: write` permission.
No
See also [the GH doc about permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token)
=> Add pull-requests permissions to benchmark workflow

.github/workflows/benchmark.yml, benchmarking/package.json, scripts/run_node.sh
- Bugfix
If the benchmarking tests fail to start a madara node, the artillery tests keep retrying the connection and never end. This causes the benchmarking test to keep running and never fail.
Resolves: #498 
- Instead of using `cargo run` in the `Run benchmark` step of the workflow, we can now use `npm run test:ci` as it's more standard and any changes in CI testing will automatically reflect in benchmarking.
- `npm run test:ci` command uses the `concurrently` package to start the node (1) and run the tests (2). The command has now been configured to kill other commands if any one of the command fails (-k option). 
- If the node fails, the benchmarking fails and exits with code 1. 
- If the node runs, the …
=> bugfix: fixed the endless loop in benchmarking if node start fails

.github/workflows/benchmark.yml, benchmarking/scripts/metrics.js
The spec of the host machines are not reported in the benchmark
Spec are added in the tooltip for each data point.
No
The GH action actually dumps the data in the follows [data file](../blob/gh-pages/dev/bench/data.js)
When needed, we could update the default FE [index.html](../blob/gh-pages/dev/bench/index.html) to do more data viz.
=> Add host spec in benchmark

infra/docker/docker-compose.yml
This PR contains some small improvements in the docker-compose performance.
Feature
- Feature
- There are warnings while running the `docker-compose` when not running it in amd64 architectures (tested in a Mac M1) due to using `paritytech/ci-linux` as the base container
- When you run amd64 containers on Mac, they are runned with some emulator, which leads Cargo to use way more memory ([users.rust-lang.org](https://users.rust-lang.org/t/cargo-uses-too-much-memory-being-run-in-qemu/76531), [rust-lang/cargo#10781](https://github.com/rust-lang/cargo/issues/10781)). In some systems, the `cargo build --release` will crash while updating the crates.io index
Resolves: #NA
- Specified the …
=> feat: Improve docker-compose performance

crates/primitives/starknet/src/execution/contract_class_wrapper.rs, crates/primitives/starknet/src/execution/mod.rs, crates/primitives/starknet/src/execution/program_wrapper.rs
Fixes the deserialising of a `ProgramWrapper`.
- Bugfix
- Testing
The `ProgramWrapper` cannot be deserialised and fails on the keys for the `constants` field.
Resolves: #NA
The `ProgramWrapper` can be deserialised without failing.
- Add `serde(try_from = "String")` for the `StringWrapper` structure.
- Add testing for serialise and deserialise of the `ContractClassWrapper`.
No
=> fix: program deserialising

crates/client/mapping-sync/src/sync_blocks.rs, crates/client/rpc/src/lib.rs, crates/pallets/starknet/src/lib.rs, crates/primitives/starknet/src/block/mod.rs, crates/primitives/starknet/src/tests/block.rs, crates/primitives/starknet/src/tests/mod.rs, crates/primitives/starknet/src/tests/state.rs
Refactoring (dev)
Resolves: https://github.com/keep-starknet-strange/madara/issues/499
Now the `BoundedVec` is passed literally instead of the `BlockTransactions` enum. The only place using the new `BlockTransactions` type is `Block`. Maybe `BlockTransactions` should be removed altogether.
No
=> remove Hashes from BlockTransactions enum

Cargo.lock, crates/client/rpc-core/src/utils.rs, crates/client/rpc/src/lib.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/deploy_account_tx.rs, crates/pallets/starknet/src/tests/mock.rs, crates/primitives/starknet/Cargo.toml, crates/primitives/starknet/src/crypto/commitment/mod.rs, crates/primitives/starknet/src/tests/crypto.rs, crates/primitives/starknet/src/transaction/types.rs, crates/runtime/src/lib.rs
- Bugfix
X Feature
- Testing
The address of the future deployed account is currently calculated in the RPC when submitting a deploy account transaction. This needs to be moved to the runtime.
Resolves: #500 
- removed `sender_address` from `DeployAccountTransaction`
- updated the `from_deploy` function of `DeployAccountTransation` impl
- remove the calculation from client/rpc-core/src/utils.rs
THIS IS A DRAFT PR. 
I NEED TO CLEAN THE CODE BEFORE MERGING.
=> feat: move calculation of deployed account address #500

crates/client/rpc/src/lib.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/primitives/starknet/src/transaction/mod.rs, crates/primitives/starknet/src/transaction/types.rs, tests/tests/test-rpc/test-starknet-rpc.ts, tests/tests/test-rpc/types.ts
`TransactionReceiptWrapper` structure contains the block hash and block number. This should not be present in the structure and provides nothing but redundant information.
- Testing
The `TransactionReceiptWrapper` structure contains a `block_hash` and a `block_number` field which provide nothing but redundant information.
Resolves: #543 
Useless fields `block_hash` and `block_number` are removed.
- Remove fields block hash and block number.
- Update testing
No
=> fix: remove block information from tx receipt fields

Cargo.lock, Cargo.toml, crates/client/rpc-core/Cargo.toml, crates/client/rpc-core/src/lib.rs, crates/client/rpc/src/lib.rs, tests/tests/test-rpc/test-starknet-rpc.ts
The `FieldElement` structure is returned raw from the RPC, causing a serialization to a decimal string instead of a hexadecimal string. Additionally, certain endpoints did not have the `block_id` argument correctly located in the function's arguments.
- Bugfix
Any RPC endpoints returning a `FieldElement` (ex: getNonce, getStorageAt,...) will return a decimal string instead of a hexadecimal string.
Resolves: #NA
RPC endpoints previously returning a `FieldElement` now return a wrapper `Felt` (as done in starknet-rs), which allows the field element to be serialized as a hexadecimal string.
- Update `FieldElement` serialization
- Update `block_id` order in RPC functions arguments.
No
=> fix: serialize field element to hex

infra/docker/Dockerfile
Docker image build is KO on amd64
Resolves: #NA
Docker image build is OK on amd64
- Add clang-11 and g++ installation in Dockerfile builder stage.
No
=> Fix docker image build on amd64

crates/client/rpc-core/src/lib.rs, crates/client/rpc/src/lib.rs, crates/client/storage/src/overrides/mod.rs, crates/client/storage/src/overrides/schema_v1_override.rs, crates/primitives/starknet/src/execution/felt252_wrapper.rs, crates/primitives/starknet/src/storage/mod.rs
The chain id is currently retrieved using the runtime API. This PR offloads the runtime by retrieving the chain id via the storage override.
Chain id is retrieved using the runtime API.
Resolves: #541 
Chain id is retrieved via a storage query.
- Query chain id via the storage
- Replace helper function `chain_id_str` by `from_utf8` implementation for `Felt252Wrapper`
No
=> feat: optimize chain id retrieval

crates/primitives/starknet/src/execution/felt252_wrapper.rs, tests/tests/test-rpc/test-starknet-rpc.ts
Update the `from_utf8` implementation for `Felt252Wrapper` in order to remove leading nul chars.
- Bugfix
- Testing
utf-8 decoding implementation for `Felt252Wrapper` does not trim leading nul chars, leading to "SN_GOERLI" to be decoded to "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0SN_GOERLI".
Resolves: #NA
utf-8 encoding removes any leading nul chars from the decoded String.
- Update decoding
- Add test for decoding
No
=> fix from utf8 function for felt252

Cargo.lock, Cargo.toml, crates/runtime/Cargo.toml, crates/runtime/src/lib.rs, crates/runtime/src/pallets.rs
Remove the `utility` pallet. We added it in the first place to be able to submit batch of extrinsics (in benchmarks). But we are not using it anymore.
Removing it reduce some unnecessary complexity and dependency.
=> 🔥 remove `pallet_utility`

Cargo.lock, Cargo.toml, crates/node/Cargo.toml, crates/node/src/benchmarking.rs, crates/node/src/chain_spec.rs, crates/node/src/rpc/mod.rs, crates/pallets/starknet/Cargo.toml, crates/runtime/Cargo.toml, crates/runtime/src/config.rs, crates/runtime/src/lib.rs, crates/runtime/src/pallets.rs
Remove unused `pallet_transaction_payment`. In previous versions we wanted to use it to handle transaction fees, but we ended up doing it manually for efficiency.
=> 🔥 remove `pallet_transaction_payment`

Cargo.lock, Cargo.toml, benchmarking/scripts/starknet-erc20.yml, crates/client/block-proposer/Cargo.toml, crates/client/block-proposer/src/lib.rs, crates/client/db/Cargo.toml, crates/client/mapping-sync/Cargo.toml, crates/client/rpc-core/Cargo.toml, crates/client/rpc/Cargo.toml, crates/client/storage/Cargo.toml, crates/node/Cargo.toml, crates/node/src/service.rs, crates/pallets/starknet/Cargo.toml, crates/primitives/starknet/Cargo.toml, crates/runtime/Cargo.toml
Extract the code from [subtrate basic authorship](https://github.com/paritytech/substrate/tree/master/client/basic-authorship) and integrate it in Madara client.
Changes summary:
- create new crate `mc-block-proposer` in `crates/client/block-proposer`
- adapt `Proposer` implementation logic
- remove hashing of extrinsics to log information on the proposed block (performance optimization and less verbose logging)
- remove unneeded telemetry reports
- remove `include_proof_in_estimation` field
=> ✨ internalize block proposer logic

crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/current_block.rs
- Bugfix
Resolves: #564
- Change the `TimestampProvider` to use `UnixTime`
- Update test to expect new behaviour
Maybe, @abdelhamidbakhta wdyt?
=> fix: use `UnixTime` instead of `Time`

Cargo.lock, Cargo.toml
Using [`starknet-rs`](https://github.com/xJonathanLEI/starknet-rs) crates from GitHub directly due to staled versions on crates.io.
A previous merged attempt (#318) tried to do the exact same thing, but was later reverted due to the need for using crates not being maintained on crates.io.
All [`starknet-rs`](https://github.com/xJonathanLEI/starknet-rs) crates are downloaded from crates.io.
We can do this now due to support for jsonrpc spec 0.3.0 being merged (https://github.com/xJonathanLEI/starknet-rs/pull/396) into `master` and released to crates.io.
No
N/A
=> chore: use starknet-rs crates from crates.io

.gitignore, .vscode/settings.json, .vscode/tasks.json
- Code enchancement
The `.vscode` directory was deleted, but as decided on chat, we must bring it back.
Resolves: #NA
Adds `.vscode` back.
No
=> chore: add .vscode back 🚀 

tests/tests/test-starknet/test-starknet-extrinsics.ts, tests/util/starknet.ts
- Testing
The current extrinsic testing just depends upon event emission, the testing should be more dependent on the state changes that calls to these extrinsic calls should result in { have been elaborated in #617  }.
The current implementation of[ deployTokenContractUDC](https://github.com/keep-starknet-strange/madara/blob/d1c45e178c05e1f718fcd4c783c735d9c12f0f02/tests/util/starknet.ts#L349) also has a bug, where the wrong value for `unique` is provided { have been described in #630  }
Resolves: #617 , #630 
Extrinsic testing involves checking for real state transitions that should result from calls to these extrinsic.
Example: 
- check for a change in equivalent balance in case of ERC20/ERC721 transfer/mint …
=> chore: enhance extrinsic testing 🚀 

Cargo.lock, crates/client/rpc-core/src/utils.rs, crates/client/rpc/src/lib.rs, crates/primitives/starknet/Cargo.toml, crates/primitives/starknet/src/transaction/mod.rs, crates/primitives/starknet/src/transaction/types.rs, crates/primitives/starknet/src/transaction/utils.rs
Dev work to refactor the Broadcasted Transaction conversions to Transactions into try_from implementations on the primitive types themselves in order to be more rustlike.
Uses functions from utils to convert Broadcast Transactions into normal transactions
Resolves: #552 
Removes the functions
- to_declare_tx
- to_deploy_account_tx
- to_invoke_tx
Try_from implementations added
No
=> broadcast transaction conversions refactor

Cargo.lock, crates/client/rpc/Cargo.toml, crates/client/rpc/src/events/mod.rs, crates/client/rpc/src/lib.rs, crates/node/src/rpc/mod.rs, crates/node/src/service.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/declare_tx.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/pallets/starknet/src/tests/l1_message.rs, tests/tests/test-rpc/test-starknet-rpc.ts
Update the `pendingTransactions` endpoint in order to include transactions that are currently in the `future` pool.
- Bugfix
The `pendingTransactions` endpoint will only return the transactions that have been placed in the `ready` queue, missing the transactions from the `future` queue (see [docs](https://docs.substrate.io/learn/transaction-lifecycle/#validating-and-queuing-transactions)).
Resolves: #NA
The rpc endpoint returns all transactions from the pool, in `ready` or `future` queue.
- Added the pool graph instance to the Starknet RPC structure in order to gain access to the `future` transaction queue
No
=> fix: add pool futures to pending transactions

docs/faucet-setup.md, infra/starknet-stack/docker-compose.yml
- Bugfix
The Starkcet faucet fails to interact with Madara and collect faucet funds.
Resolves: #579 
- Madara doesn't support `0x100000000000000000000000000000001` version for estimateFee. The issue can be tracker [here](https://github.com/keep-starknet-strange/madara/issues/646). So we need to manually change the version to `0x1` when estimating fees.
- Docs have been added giving instructions on how to use the faucet 
No
=> bugfix: starkcet faucet not working

docs/sharingan-starter-pack.md
Add the hardware setup required to run Madara.
It is based on the version used for Sharingan, and may vary in the future.
But it's impressive that on a VM with `2 vCPU` and `2GB RAM`, it runs so nicely.
We just have a point with the peers, it looks like substrate keep some peers in memory or I don't know, but it consumes more resources at the startup. This is less true when we are at the head of the chain.
=> docs: add hardware requirements for Sharingan

crates/primitives/starknet/src/execution/contract_class_wrapper.rs, docs/getting-started.md
We want to make the default compiler version easily configurable in the ProgramWrapper conversion
- Other (please describe): Enhancement
Hardcoded value of 0.11.2
Resolves: #670 
Compiler version can be specified when building Madara
For example:
`COMPILER_VERSION=0.12.0 cargo build`
No
=> feat: Configurable compiler version in ProgramWrapper

cairo-contracts/build/emit_single_event.json, cairo-contracts/src/test_contracts/emit_single_event.cairo, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/erc20.rs, crates/pallets/starknet/src/tests/invoke_tx.rs
- Bugfix ✅ 
- Feature
- Testing
Event emission does not recursively move through the inner_calls of each call_info to extract events.
Resolves: #669 
Event emission does recursively move through the inner_calls of each call_info to extract events.
-
-
-
=> emit events should recurse thru inner calls

crates/client/rpc/src/errors.rs, crates/client/rpc/src/lib.rs, tests/tests/constants.ts, tests/tests/test-rpc/test-starknet-rpc.ts
Add support for checking at RPC to look for already declared classes, and not proceed if they exist.
- Feature
The current sequencer behavior is to proceed with all declare class calls without checking if the class is already declared or not. 
According to the s[pec](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json#L146), this should result in an error.
Resolves: #663 
- checks whether the class already exists or not
- if exists, returns the error code according the spec
- a test has also been included to check this behavior for RPC
no
=> feat: add support at rpc to check for already declared class 🚀

benchmarking/package.json, benchmarking/scripts/combine-metrics.js, benchmarking/scripts/functions.js, benchmarking/scripts/metrics.js, benchmarking/scripts/starknet-erc721.yml
add erc721 `mint` benchmarks for Madara
- Feature
Currently, we only have benchmarks for erc20, and benchmarks for ERC721 `mint` aren't present.
Resolves: #502  #692 
benchmarks for ERC721 have been added.
No
- The code has been refactored in a way, that it requires no changes on the GitHub workflow side of the thing, as it still makes available the "test:ci" npm script, and outputs the benchmark to the same "benchmarking/report/metrics.json" file.
- The same file metrics.json will now have data to render benchmarks for both ERC20 `transfers` and ERC721 `mints`.
=> feat: add erc721 `mint` benchmarks

tests/tests/test-rpc/test-starknet-rpc.ts
Currently, there are ESLINT warnings generating noise on PRs.
We have some pending typescript tests which is why the imports removed and unused code were there in the first place. We should temporarily silence these warnings to avoid so much noise on open PRs.
- Other (please describe): Eslint fix
Warning on open PRs
No more warnings. 
Once we implement the missing tests
We can import `RPC, stark` and also remove the 307 line.
No
=> Chore: cleanup of eslint warning on typescript tests

Cargo.lock, Cargo.toml, crates/client/transaction-pool/Cargo.toml, crates/client/transaction-pool/src/api.rs, crates/client/transaction-pool/src/enactment_state.rs, crates/client/transaction-pool/src/lib.rs, crates/node/Cargo.toml, crates/node/src/chain_spec.rs, crates/runtime/src/pallets.rs
Go back to `polkadot-v0.9.43` version of substrate. We highly suspect the move to the `master` branch caused some flaky bugs for consensus when we tested on Sharingan testnet.
We will test again after downgrading the version.
=> ⬇️ substrate `polkadot-v0.9.43`

crates/node/src/command.rs
Dev flag adds node as authorities with `alice` key
=> fix: remove dev flag used previously

docs/sharingan-starter-pack.md
Bump to 7.1 version (thanks @d-roak for the fix).
Also minor changes:
1. change the node explorer URL as Cartridge one seems out of sync.
2. docker volume creation adjusted.
3. some missing ports migrated to `9944`.
=> docs: update sharingan starter pack bump to 7.1

crates/node/src/command.rs
If `--dev` flag is specified, ignore madara usual cache folder
=> fix: running madara with dev flag

Cargo.lock, Cargo.toml, crates/client/rpc-core/src/tests.rs, crates/client/rpc-core/src/utils.rs, crates/pallets/starknet/src/tests/call_contract.rs, crates/pallets/starknet/src/tests/declare_tx.rs, crates/pallets/starknet/src/tests/deploy_account_tx.rs, crates/pallets/starknet/src/tests/erc20.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/pallets/starknet/src/tests/l1_message.rs, crates/pallets/starknet/src/tests/mod.rs, crates/primitives/starknet/src/crypto/commitment/mod.rs, crates/primitives/starknet/src/tests/block.rs, crates/primitives/starknet/src/tests/crypto.rs, crates/primitives/starknet/src/tests/transaction.rs, crates/primitives/starknet/src/transaction/mod.rs, crates/primitives/starknet/src/transaction/types.rs, crates/primitives/starknet/src/transaction/utils.rs
- Bugfix
- Feature
Estimate fee with version `0x100000000000000000000000000000001` doesn't work. Starknet-rs has added support for it and this PR integrates it.
Resolves: #646 
- Estimate fee works correctly now
- Once `dev/query_tx_version` is merged in `starknet-rs`, I will update the packages in this PR and we can merge
No
=> added `is_query` to handle estimate fee

Cargo.lock
When running in wasm execution, fail to decode `ContractClass` from storage.
Is now able to decode successfully
=> build: update deps to non bugged cairo-rs

README.md
- Incorrect link in docs (app instead of infra)
- Correct link to madara-infra repo
No
N/A
=> Fixed madara-infra link in README

CHANGELOG.md, examples/rpc/hurl.config
- Bugfix
When testing RPC with a local node, the error is like:
```
hurl --variables-file examples/rpc/hurl.config  --test examples/rpc/starknet/starknet_chainId.hurl
examples/rpc/starknet/starknet_chainId.hurl: Running [1/1]
error: Assert status code
--> examples/rpc/starknet/starknet_chainId.hurl:10:6
|
10 | HTTP 200
|      ^^^ actual value is <403>
|
examples/rpc/starknet/starknet_chainId.hurl: Failure (1 request(s) in 8 ms)
```
```
hurl --variables-file examples/rpc/hurl.config  --test examples/rpc/starknet/starknet_chainId.hurl
examples/rpc/starknet/starknet_chainId.hurl: Running [1/1]
examples/rpc/starknet/starknet_chainId.hurl: Success (1 request(s) in 5 ms)
--------------------------------------------------------------------------------
Executed files:  1
Succeeded files: 1 …
```
=> Update RPC URL to use localhost instead of 0.0.0.0 in hurl.config file

CHANGELOG.md, tests/tests/test-starknet-rpc/test-events.ts
This is a fixup for #1001 
Event ordering affects continuation token returned when iterating over filtered events. This patch fixes the broken test.
=> Tests: fix expected event idx in continuation tokens

CHANGELOG.md, crates/client/rpc-core/src/utils.rs, tests/tests/test-starknet-rpc/test-contracts.ts
Removed double JSON serialization for Cairo legacy program code.
- Bugfix
Calling RPC `getClassAt` with a Cairo legacy contract address doesn't return a valid compressed program code.
Resolves: #1032
Calling RPC `getClassAt` with a Cairo legacy contract address returns a valid compressed program code.
No
=> fix: #1032: RPC: getClassAt doesn't follow specification for Cairo legacy program code

starknet-rpc-test/Cargo.toml, starknet-rpc-test/get_class_hash_at.rs
Add test case in rust for `getClassHashAt` route.
Parent issue: #904 
- Testing
Resolves: #NA
Contains the following tests:
No
=> test: #904: add get_class_hash_at.rs

starknet-rpc-test/Cargo.toml, starknet-rpc-test/get_class.rs, starknet-rpc-test/src/fixtures.rs, starknet-rpc-test/src/lib.rs
Add test cases in rust for `getClass` route.
Parent issue: #904 
- Testing
Resolves: #NA
Contains the following tests:
No
Test for sierra class have been disabled and should be enabled once #992  by @tdelabro will be merged.
=> test: #904: add get_class.rs

.vscode/launch.json, CHANGELOG.md, crates/pallets/starknet/src/tests/call_contract.rs, crates/pallets/starknet/src/tests/declare_tx.rs, crates/pallets/starknet/src/tests/deploy_account_tx.rs, crates/pallets/starknet/src/tests/erc20.rs, crates/pallets/starknet/src/tests/events.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/pallets/starknet/src/tests/mod.rs, crates/pallets/starknet/src/tests/utils.rs, crates/primitives/starknet/src/execution/call_entrypoint_wrapper.rs, crates/primitives/starknet/src/fees/mod.rs, crates/primitives/starknet/src/tests/crypto.rs, crates/primitives/starknet/src/transaction/mod.rs, crates/primitives/starknet/src/transaction/types.rs, tests/tests/test-starknet-rpc/test-cairo-1.ts, tests/tests/test-starknet-rpc/test-transactions.ts, tests/util/starknet.ts
- fixes incorrect initial_gas for transactions which would cause transactions to go through in the blockifier even if enough gas was not present
- fixed a bug where fees wouldn't be charged if max_fee was 0
=> Initial gas fix

CHANGELOG.md, crates/primitives/starknet/src/transaction/types.rs
class_hash was being returned instead of `compiled_class_hash` in RPCTransaction which is used in get_block_with_txs
=> fix: correct value of compiled_class_hash in RPCTransaction

starknet-rpc-test/Cargo.toml, starknet-rpc-test/get_transaction_by_blockid_and_index.rs
Add test cases for getTransactionByBlockIdAndIndex.
Parent issue: https://github.com/keep-starknet-strange/madara/issues/904
Rebase PR: https://github.com/keep-starknet-strange/madara/pull/1063
- Testing
Resolves: #NA
Rust impl for test get_transaction_by_block_id_and_index:
- Return an error for a nonexisting block
- Return an error for an out of block index
- Compare with getBlockWithTx and make sure order is the same
No
=> add getTransactionByBlockIdAndIndex tests to e2e rust tests

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/client/rpc/src/errors.rs, crates/client/rpc/src/lib.rs, crates/primitives/starknet/src/tests/transaction.rs, crates/primitives/starknet/src/transaction/types.rs, tests/tests/test-starknet-rpc/test-block.ts
- bump starknet-core to 0.6.0
- remove InvokeTransactionV0 (it's deprecated now)
- return `ValidationFailure` if there's an error in signature validation
=> feat: update starknet-core

CHANGELOG.md, rust-toolchain.toml
My rust analyzer stopped working after #1068 and I didn't understand why.
With this, I can just run `cargo install` in the project and it will install the correct version
=> build: add rust-analyzer to toolchain components

.codecov.yml, CHANGELOG.md
The issue #1072 gives a valid reason for this increase. I was looking through the repo and saw this smol issue hanging around.
- Other (please describe): CI tweak
Threshold is 0%
Resolves: #1072 
Increased to 1%
No
=> dev: increase threshold for codecov to 1%

CHANGELOG.md, crates/primitives/starknet/src/transaction/compute_hash_tests.rs
Adds tests for all transaction type hashing. Closes #1114
- Testing
No
=> chore: add tx hashing tests

CHANGELOG.md, crates/primitives/transactions/Cargo.toml
The transactions crate was missing the std feature for 4 crates, causing the tests in the crate to compile in no_std, which doesn't work. As a result, the crate tests cant be run from within the crate.
- Bugfix
transactions tests can't be run in `crates/primitives/transactions`
The tests can be run within the crate
No
=> fix: transactions crate std import

CHANGELOG.md, crates/primitives/transactions/src/execution.rs
Adds tests for checking the correct usage of the simulated tx version offset. 
Additionally, a minor refactoring, adds a trait used for applying the version offset for all different program paths.
These changes close #1115 
- Testing
- Refactoring
No
=> chore: add simulate tx version offset tests

crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/l1_message.rs, crates/pallets/starknet/src/tests/mod.rs, crates/pallets/starknet/src/tests/transaction_validation.rs
=> Tests for `validate_unsigned` for L1 Messages transactions

CHANGELOG.md, starknet-rpc-test/Cargo.toml, starknet-rpc-test/estimate_fee.rs, starknet-rpc-test/src/fixtures.rs
- Testing
Currently, no test for the rpc method: `estimate_fee`.
Resolves: #1151
- Adding testing for estimate_fee
No
=> test: add e2e test for rpc's estimate_fee

CHANGELOG.md, starknet-rpc-test/src/lib.rs
https://github.com/keep-starknet-strange/madara/actions/runs/6495558436/job/17642025203?pr=1182
https://users.rust-lang.org/t/runtime-dropped-the-dispatch-task/91915/8
=> fix(starknet-rpc-test): don't share reqwest client across test runtimes

docs/getting-started.md
This PR updates `getting-started.md` to follow the changes introduced in #1165:
- the behavior of node's `setup` command was changed:
- using one of the switches became [mandatory](https://github.com/keep-starknet-strange/madara/blob/29a8b112f5a09dc2ad9a29989b95b7e3a15623ec/crates/node/src/commands/setup.rs#L19): either `--from_remote` or `--from_local`
- `--chain` should be specified if you intend to run the node in dev mode, because `--dev` sets `--chain=dev` implicitly
- `run` command was uplifted (its arguments apply to the node directly)
=> docs: fix setup and run commands in `getting-started.md`

CHANGELOG.md, crates/primitives/commitments/src/lib.rs
Corrected typo here: https://github.com/keep-starknet-strange/madara/blob/ee2602aed93eb54b9582f67ff926b16f403a69df/crates/primitives/commitments/src/lib.rs#L164
=> fix event commitment documentation typo

CHANGELOG.md, Cargo.lock, crates/node/src/chain_spec.rs, crates/node/src/cli.rs, crates/node/src/command.rs, crates/node/src/commands/run.rs, crates/node/src/service.rs, crates/runtime/Cargo.toml, crates/runtime/src/config.rs, crates/runtime/src/pallets.rs
- fix(service): confusing message when node starts (output the actual sealing method being used)
- refactor: how the sealing mode is passed into runtime
- feat: finalization for instant sealing
New sealing mode `instant-finality` is added to the cli (kudos to @tdelabro ) for command parsing:
```rust
enum Sealing {
Manual,
Instant,
InstantFinality,
}
``` 
Internally sealing mode is represented with the following domain model:
```rust
enum SealingMode {
#[default]
Default,
Manual,
Instant {
finalize: bool,
},
}
``` 
`let (command_sink, commands_stream) = mpsc::channel(1000);` is adjusted to create for `SealingMode::Manual` only.
Closes #1144
=> Refactor non-default sealing

CHANGELOG.md, crates/client/db/src/lib.rs, crates/client/db/src/mapping_db.rs, crates/client/mapping-sync/src/lib.rs, crates/client/mapping-sync/src/sync_blocks.rs, crates/client/rpc/src/lib.rs, crates/node/src/command.rs, crates/node/src/commands/run.rs, crates/node/src/service.rs, crates/primitives/block/src/lib.rs, crates/primitives/transactions/src/to_starknet_core_transaction.rs
This allows trading a bit of the memory footprint of Madara for better response time (specifically in the RPC client implementation).
This is a new feature.
Nothing is cached and transaction hashes are re-computed every time they are needed.
Resolves: #1180 
Transaction hashes are not stored along with block data in the database under the column `STARKNET_TRANSACTION_HASHES_CACHE`.
No.
Currently, the flag is introduce as a simple boolean flag.
```Rust
#[clap(long, action)]
cache: bool,
```
In the future, it might be good to make this a vector of flags, which could optionally enable caching for only *some* parts of the database. Right now it's only for transaction hashes.
=> Add the `--cache` option, allows caching more information into the database

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/block.rs, crates/primitives/fee/Cargo.toml, crates/primitives/fee/src/lib.rs, crates/primitives/transactions/src/execution.rs
update dependencies, including blockifier where we previously replaced float by FixedU128.
We also come back to an hashmap for the vm_ressource_fee_cost, for better integration with blockifier's type
=> chore: rework vm ressource fee

CHANGELOG.md, crates/client/rpc/src/events/mod.rs, crates/client/rpc/src/lib.rs
- Bugfix
- Feature
-  ✅  Refactoring (no functional changes, no API changes) 
- Testing
StarknetRpcApi's error handling must follow the starknet OpenRPC specifications. Debugging information of what is causing `InternalServerError` is not surfaced to the dev-user.
Resolves: #1214 
We add `error!` logging of the inner error, along with a bit of context.
No.
=> dev(StarknetRPC): log error we receive from node before mapping to InternalServerError

.github/workflows/pull-request.yml, .github/workflows/push.yml, .github/workflows/starknet-js-tests.yml, CHANGELOG.md
This introduces some tests to ensure compatibility with the starknet-js package. This PR completes #1148 
The corresponding testing code has been moved to[ this repo](https://github.com/petscheit/madara-js-tests)
- Testing
This PR introduces the following tests
- Declare and deploy v0 & v1 contracts to madara
- Read state from smart contacts & via provider api
- Invoke transactions & decode events
- Estimate fees for declare, deploy and invoke
=> Add starknetjs compatibilty tests to CI

CHANGELOG.md, crates/client/transaction-pool/Cargo.toml, crates/client/transaction-pool/src/tests.rs, crates/client/transaction-pool/tests/pool.rs
Testing
No testing of the transaction pool logic.
Implement unit tests for the transaction pool logic.
It's essentially a copy/paste of tests coded [here](https://github.com/paritytech/substrate/blob/master/client/transaction-pool/tests/pool.rs) and [there](https://github.com/paritytech/substrate/blob/master/client/transaction-pool/src/tests.rs).
No
Please note:
- I was unsure of what to do with the leading copyright comments, so I left them,
- There were two crates absent from Madara's `Cargo.toml`, so I added them to `transaction-pool`'s `Cargo.toml`. I'm unsure wether they should be added to the main repo's dev-dependencies instead. They are:
1. `substrate-test-runtime`, and
2. `substrate-test-runtime-transaction-pool`.
=> copy-paste transaction-pool tests from substrate

CHANGELOG.md, crates/client/rpc/src/lib.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/runtime_api.rs, crates/pallets/starknet/src/tests/query_tx.rs, crates/primitives/fee/src/lib.rs, crates/runtime/src/lib.rs
This PR fixes errors which occur when sending transactions through Starknet Foundry/starknet.rs.
Currently, transactions sent from starknet-rs fail, since starknet-rs sends `is_query: false` for their estimate calls.  
Resolves: #1168 
- Remove the `is_query` check in the estimate function. According to the chat in the starknet-rs, this will be changed later(see [the discussion](https://t.me/starknet_rs/4880)) so I added an error log indicating this. 
- Consequently, `is_query` can't be defaulted further along the code path since it is used in the construction of the hash used in signing/verifying. We accept the `is_query` value that was sent instead.
No, because the `is_query` value which was sent is used.
This is also related to …
=> Alter transaction checks for starknet-rs/foundry compatibility

CHANGELOG.md, crates/client/rpc/src/lib.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/runtime_api.rs, crates/pallets/starknet/src/tests/query_tx.rs, crates/runtime/src/lib.rs, starknet-rpc-test/estimate_fee.rs
- Feature
Allow to pass a vector of transactions for fee estimation. Needed for instance for compatibility with the Argent wallet. 
Currently we accept only 1 transaction to estimate the fee and the state rolls back to initial state after each estimation. 
Resolves: [issue](https://github.com/keep-starknet-strange/madara/issues/1202)
We pass a vector of transaction to the `estimate_fee` function
=> estimate fee for bulk transactions

Dockerfile
Add `libprotobuf-dev` to builder stage of Dockerfile.
- Bugfix
Docker release fails after 0.2.0(https://github.com/keep-starknet-strange/madara/actions/workflows/release.yml) with error message:
```
...
359.7    Compiling scale-decode v0.7.0
360.0 error: failed to run custom build command for `celestia-proto v0.1.0 (https://github.com/eigerco/celestia-node-rs?rev=bd6394b66b11065c543ab3f19fd66000a72b6236#bd6394b6)`
360.0 
360.0 Caused by:
360.0   process didn't exit successfully: `/madara/target/release/build/celestia-proto-54d657cd8f692a98/build-script-build` (exit status: 1)
360.0   --- stderr
360.0   Error: protoc failed: google/protobuf/descriptor.proto: File not found.
360.0   gogoproto/gogo.proto: Import …
```
=> Update Dockerfile, add `libprotobuf-dev` 

.github/workflows/starknet-js-tests.yml, .github/workflows/starknet-rpc-tests.yml, .gitmodules, CHANGELOG.md, crates/node/src/commands/setup.rs
- Removes `madara-app` and `madara-dev-explorer` submodules are these are deprecated and not maintained for a while. Focus should be on putting madara into production.
- Fixes setup in CI which was fetching from remote. If the config was changed in the PR then potential failing tests would not be caught until merged on main.
=> 🗑️ cleanup

CHANGELOG.md, Cargo.lock, crates/client/rpc-core/src/lib.rs, crates/client/rpc/Cargo.toml, crates/client/rpc/src/lib.rs
Dojo wasn't aware of pending transactions in the Madara tx pool. Pending tx was returing as not found. 
We loop for 1 minute to make sure the transaction is processed. 
No
=> fix(starknet_rpc/get_transaction_receipt): async loop to get pending tx

CHANGELOG.md, Cargo.lock, crates/client/rpc-core/src/lib.rs, crates/client/rpc/Cargo.toml, crates/client/rpc/src/lib.rs, crates/node/src/rpc/mod.rs
https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_write_api.json
StarknetRPC specs are split between multiple groups. This PR imitate this separation by creating two traits
=> chore: split starknetRPC in two traits to follow openRPC spec definition

CHANGELOG.md, Cargo.lock
Hints were serde as vec, instead of BTreeMap in ContractClassV1Internal
=> build: update blockifier so no more divergent substrate block hash

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/client/rpc/src/errors.rs, crates/client/rpc/src/events/tests.rs, starknet-rpc-test/get_events.rs, starknet-rpc-test/get_transaction_receipt.rs, starknet-rpc-test/src/lib.rs, starknet-rpc-test/src/utils.rs
Bump the current version of starknet-rs in order to make use of the `Eq` and `PartialEq` derives.
- Feature
`EmittedEvents` and `Events` don't implement the `Eq` and `PartialEq` traits.
Resolves: #1094
`EmittedEvents` and `Events` can now be compared with `==` operator.
No
=> dev: bump starknet rs

docs/CONTRIBUTING.md, docs/contributor-starter-pack.md, docs/project-structure.md, docs/sharingan-starter-pack.md
=> chore: fix typos

CHANGELOG.md, Cargo.lock, starknet-e2e-test/Cargo.toml, starknet-e2e-test/README.md, starknet-e2e-test/ethereum_e2e_settlement.rs
Bugfix
`tempdir` crate has been deprecated, as mentioned in issue #1337 
Resolves: use `tempfile` instead
=> fix: Replace `tempdir` with `tempfile` as suggested in issue #1337

CHANGELOG.md, Cargo.lock, crates/client/data-availability/src/lib.rs, crates/node/src/service.rs, docs/rpc-contribution.md
There is no ordering between `prove_current_block` and `update_state`, any function can be called first. For context, `prove_current_block` updates the state diff in the db and `update_state` fetches those diffs. 
Case 1: `prove_current_block` is called first, DA works fine `store_state_diff` is called before `state_diff` which gets the state diff
Case 2: `update_state` is called first, DA throws an error as it first calls `state_diff` and then `store_state_diff`.
Since in the validity case, the proof be dependent on the DA, we should be calling `update_state` first. So we need to move the `store_state_diff` to update_state, call it first and then call `prove_current_block` at the end of update state.
=> fix: call proving only after update state

CHANGELOG.md, crates/client/data-availability/src/lib.rs, crates/node/src/service.rs
Publish state then prove
Resolves: #NA
prove then publish state, as in validity mode the eth core contracts update_state check for the proof
=> fix: reorder DA tasks

CHANGELOG.md, Cargo.lock, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/mock/setup_mock.rs, crates/primitives/fee/src/lib.rs, crates/runtime/Cargo.toml, crates/runtime/src/pallets.rs
Lucas needs it for https://github.com/keep-starknet-strange/snos/issues/68
It make sure that the value used in execution block context and the one in the block header are the same
=> feat: L1 gas price is configurable in the RuntimeConfig

.github/workflows/starknet-rpc-tests.yml, CHANGELOG.md, crates/client/rpc/src/events/mod.rs, crates/client/rpc/src/lib.rs, crates/pallets/starknet/runtime_api/src/lib.rs, crates/runtime/src/lib.rs
Modifies code to use the cache for `getEvents` and `getTransactionReceipt` for reading txn_hashes if `cache` flag is enabled.
=> use cache for receipts and event txs

CHANGELOG.md, docs/genesis.md, docs/project-structure.md
I've found that some of links in the documentation are outdated. The linked resource are not approachable. 
- Working links to the original resources.
No.
=> fix: update outdated links

CHANGELOG.md, starknet-rpc-test/get_state_update.rs
Those are failing and blocking the CI for other PR.
The current impl of the RPC is not the one we want. So let's disable for now.
=> test(rpc): disable state_diff work

.github/workflows/starknet-rpc-tests.yml, CHANGELOG.md, Cargo.lock, crates/client/rpc-core/src/lib.rs, crates/client/rpc/Cargo.toml, crates/client/rpc/src/events/mod.rs, crates/client/rpc/src/lib.rs, crates/client/rpc/src/runtime_api.rs, crates/client/rpc/src/trace_api.rs, crates/pallets/starknet/runtime_api/src/lib.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/simulations.rs, crates/primitives/transactions/src/compute_hash.rs, crates/primitives/transactions/src/compute_hash_tests.rs, crates/primitives/transactions/src/getters.rs, crates/primitives/transactions/src/lib.rs, crates/primitives/transactions/src/to_starknet_core_transaction.rs, crates/runtime/src/lib.rs, starknet-rpc-test/get_block_with_tx_hashes.rs, starknet-rpc-test/get_block_with_txs.rs, starknet-rpc-test/get_transaction_receipt.rs, starknet-rpc-test/src/lib.rs
=> RPC - Support for pending state

CHANGELOG.md, crates/client/rpc/src/events/mod.rs, crates/client/rpc/src/lib.rs, crates/client/storage/src/overrides/mod.rs, crates/client/storage/src/overrides/schema_v1_override.rs, crates/pallets/starknet/runtime_api/src/lib.rs, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/deploy_account_tx.rs, crates/pallets/starknet/src/tests/erc20.rs, crates/pallets/starknet/src/tests/events.rs, crates/pallets/starknet/src/tests/invoke_tx.rs, crates/pallets/starknet/src/tests/mock/setup_mock.rs, crates/primitives/storage/src/lib.rs, crates/runtime/src/lib.rs, crates/runtime/src/pallets.rs
- Feature
We store Starknet events in Substrate events which is not pretty convenient and infate [block size](https://github.com/paritytech/substrate/blob/033d4e86cc7eff0066cd376b9375f815761d653c/frame/system/src/lib.rs#L627)
Resolves: #NA
- `TxEvents` are not deleted after storing block, so that it's main storage for starknet events
- `StarkEvent`s does not stored in Substrate events
No
=> feat: move StarkEvents to storage 

CHANGELOG.md, crates/primitives/snos-output/src/codec.rs, starknet-e2e-test/src/starknet_sovereign.rs, starknet-rpc-test/src/lib.rs
Code uses `Vec::new` when it could use `Vec::with_capacity`.
Resolves: #NA
Code uses `Vec::with_capacity`.
No
=> dev: use `with_capacity`

CHANGELOG.md, Dockerfile
- Bugfix:  Madara Docker Build failing due to incorrect Madara binary file location
Madara Docker build fails due to incorrect madara bin location 
Resolves: 
Building of madara Docker image 
In Madara docker file, it is building Madara with --release tag 
But in COPY cmd, it  tries to copy it from production folder instead of release that throws file no found error. 
No
=> BugFix: Madara Docker Build failing due to incorrect Madara binary location

CHANGELOG.md, crates/client/db/src/da_db.rs, crates/client/rpc/src/lib.rs, crates/client/rpc/src/trace_api.rs, crates/pallets/starknet/runtime_api/src/lib.rs, crates/pallets/starknet/src/simulations.rs, crates/pallets/starknet/src/tests/re_execute_transactions.rs, crates/primitives/simulations/src/lib.rs, crates/runtime/src/lib.rs, starknet-rpc-test/Cargo.toml, starknet-rpc-test/add_declare_transaction.rs, starknet-rpc-test/get_state_update.rs
- Feature
getting data from DA 
Resolves: #1594
simulating transactions to get state diff
No
=> dev: impl `get_state_updates` by re executing transactions

CHANGELOG.md, crates/pallets/starknet/src/lib.rs, crates/pallets/starknet/src/tests/declare_tx.rs, crates/pallets/starknet/src/tests/deploy_account_tx.rs, crates/pallets/starknet/src/tests/invoke_tx.rs
By removing those checks we will return same errors are Starknet rather than our customs ones (when we will be able to return complex errors from runtime)
=> fix: remove unecessary checks before tx execution
