- Cargo.lock
- Cargo.toml
- pallets/starknet/Cargo.toml
- pallets/starknet/src/lib.rs
- primitives/starknet/Cargo.toml
- primitives/starknet/src/crypto/hash/mod.rs
- primitives/starknet/src/crypto/hash/pedersen.rs
- primitives/starknet/src/crypto/hash/poseidon.rs
- primitives/starknet/src/crypto/mod.rs
- primitives/starknet/src/lib.rs
Kaioshin don't have primitives that can be used in pallets.
This PR introduces Kaioshin primitives module. For now we initiate it with `kp-starknet` (Kaioshin Primitives Starknet)
> Init Kaioshin primitives

- .github/workflows/check.yml
- Cargo.lock
- pallets/starknet/src/lib.rs
- primitives/starknet/src/block/wrapper/header.rs
> Fill header fields

- .github/workflows/rustdoc.yml
- Cargo.lock
- Cargo.toml
- pallets/starknet/Cargo.toml
- pallets/starknet/src/lib.rs
- pallets/starknet/src/mock.rs
- pallets/starknet/src/tests.rs
- primitives/starknet/src/block/wrapper/header.rs
- runtime/src/lib.rs
> Get block timestamp in the wrapper block

- .github/workflows/check.yml
> fix(ci): add caching inthe ci

- pallets/starknet/src/lib.rs
> fix(starknet): fix hook for block 0

- Cargo.lock
- pallets/starknet/src/lib.rs
- pallets/starknet/src/tests.rs
- primitives/starknet/Cargo.toml
- primitives/starknet/src/block/wrapper/header.rs
- primitives/starknet/src/crypto/commitment/mod.rs
- primitives/starknet/src/crypto/hash/mod.rs
- primitives/starknet/src/crypto/hash/pedersen.rs
- primitives/starknet/src/crypto/hash/poseidon.rs
- primitives/starknet/src/crypto/merkle_patricia_tree/merkle_node.rs
- primitives/starknet/src/crypto/merkle_patricia_tree/merkle_tree.rs
- primitives/starknet/src/crypto/merkle_patricia_tree/mod.rs
- primitives/starknet/src/crypto/mod.rs
- primitives/starknet/src/lib.rs
- primitives/starknet/src/traits/hash.rs
- primitives/starknet/src/traits/mod.rs
- primitives/starknet/src/traits/transaction.rs
- primitives/starknet/src/transaction/mod.rs
- primitives/starknet/tests/crypto.rs
- Tx commitment is computed before storing the block.
> Tx commitment

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @ZePedroResende as a contributor

- .github/workflows/rustdoc.yml
- .github/workflows/test.yml
- .tarpaulin.toml
- Cargo.lock
- Cargo.toml
- crates/primitives/starknet/src/transaction/mod.rs
- rust-toolchain.toml
> feat(ci): add coverage

- crates/pallets/starknet/src/lib.rs
- crates/primitives/starknet/src/transaction/mod.rs
- crates/primitives/starknet/src/transaction/types.rs
Issue Number: #98
rename `deploy` to `deploy_account` for transactions #98
> 🚚 fix dev: rename `deploy` to `deploy_account` for transactions #98

- README.md
- autodoc.config.json
> 🚚 add benchmark gif

- README.md
> Add progress section

- .github/workflows/test.yml
> Codecov works without token (maybe)

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @drspacemn as a contributor

- .github/workflows/docker.yml
Build + Push docker image to ghcr
not pushed in ci
- build it
- push it
> build + push to ghcr

- benchmarking/README.md
A typo in benchmarking's readme: `cd .. && cargo build release` -->   `cd .. && cargo build --release`
> chore(typo): fix a typo in benchmarking's readme

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @hsyodyssey as a contributor

- README.md
> 📝 fix wrong links and restructure section ordering

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @zediogoviana as a contributor

- README.md
- docs/starknet_features_compatibility.md
> 📝 move features compatibility in separate doc

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @Matth26 as a contributor

- typescript-api/package.json
> switch @madara/api-augment to public ♻️

- .github/workflows/publish-typescript-api.yml
> fix @madara/api-augment workflow ♻️

- crates/node/src/chain_spec.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/mock.rs
- crates/primitives/starknet/src/block/serialize.rs
- crates/primitives/starknet/src/transaction/mod.rs
- crates/primitives/starknet/src/transaction/types.rs
- typescript-api/package-lock.json
Issue Number: fixes #183 
- `fee_token_address` is initialized through genesis config and stored in the pallet
> 🔧 add `fee_token_address` in genesis config

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests.rs
Fee token address cannot be changed.
Fee token address can be changed through sudo pallet.
> ✨ `set_fee_token_address` (root only)

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @glihm as a contributor

- docs/starknet_features_compatibility.md
> 📝 update features compatibility table

- README.md
- docs/getting-started.md
- 📝 refactor readme
- ✏️ fix wrong link
- 📝 remove readme title
- 📝 fix broken links
-
-
-
> 📝 fix broken links

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @0xEniotna as a contributor

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @ClementWalter as a contributor

- docs/rpc-contribution.md
Add a guide for new RPC contributors to quickly locate files and code to be added/changed.
-
-
-
> docs: add rpc-contribution.md

- README.md
> ✍ update readme

- docs/project-structure.md
> fix: fix two broken links

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @Eikix as a contributor

- .github/workflows/test.yml
> Add clippy test + switch to llvm cov

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests.rs
- crates/primitives/starknet/src/crypto/commitment/mod.rs
- crates/primitives/starknet/src/starknet_serde/mod.rs
- crates/primitives/starknet/src/transaction/mod.rs
- crates/primitives/starknet/src/transaction/types.rs
- crates/primitives/starknet/tests/crypto.rs
- crates/primitives/starknet/tests/transaction.rs
Issue Number: Fixes #236
- Fee transfer emits an event
> Add event in fee transfer

- README.md
- 📝 update readme
- 🚨 fix markdown lint
-
-
-
> 🚨 fix markdown lint

- README.md
> chore(format): fix abdel's mess

- benchmarking/scripts/functions.js
- tests/util/starknet.ts
- Benchmark uses fee token
- Benchmark uses single transfers with no validation
> fix: benchmark use fee token 🔨

- crates/pallets/starknet/src/lib.rs
We use an unnecessary hashing step for storage keys that are already hashes.
Use `Identity` when relevant.
> ⚡️ move to `Identity` for `StorageMap` when relevant

- crates/pallets/starknet/src/lib.rs
- crates/primitives/starknet/src/transaction/types.rs
- Only one tx for fee transfer which should improve performances
> refacto(starknet): change to one tx for fees

- benchmarking/README.md
- benchmarking/scripts/functions.js
- benchmarking/scripts/metrics.js
- benchmarking/scripts/starknet-erc20.yml
- crates/node/src/chain_spec.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/mock.rs
- crates/runtime/src/pallets.rs
- scripts/run_node.sh
- tests/tests/test-starknet/test-starknet-extrinsics.ts
- tests/util/setup-dev-tests.ts
- tests/util/starknet.ts
- Most extrinsics are switched to `unsigned`
- Integrations tests `test-starknet-extrinsics` have been updated to work correctly
- Improves `benchmarking/` instructions
These two posts explain quite well the tx lifecycle : [1](https://substrate.stackexchange.com/questions/2148/transactions-lifecycle), [2](https://substrate.stackexchange.com/questions/2179/why-unsigned-extrinsics)
> feat: switch to unsigned transactions ✨

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/declare_tx.rs
- crates/pallets/starknet/src/tests/deploy_account_tx.rs
- crates/pallets/starknet/src/tests/l1_message.rs
- crates/pallets/starknet/src/tests/mod.rs
closes #295 
Most errors are now properly tested
> feat: test various errors

- crates/pallets/starknet/src/blockifier_state_adapter.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/message.rs
- crates/pallets/starknet/src/offchain_worker/mod.rs
- crates/pallets/starknet/src/offchain_worker/types.rs
- crates/pallets/starknet/src/starknet_fee.rs
- crates/pallets/starknet/src/tests/invoke_tx.rs
- crates/pallets/starknet/src/transaction_validation.rs
- crates/pallets/starknet/src/types.rs
- crates/primitives/starknet/src/execution/mod.rs
Too much logic hang in `lib.rs`, and inside the `pallet` module.
- offchain worker logic is in it's own module
- `transfer_fees` moved to the `starknet_fee` module
- `impl<T: Config> Pallet<T>` moved out of the `pallet` module in `lib.rs`
- less unwrap in `lib.rs`
- `query_eth` return raw `Vec<u8>` instead of converting it to String. It was not needed as we can serialize form bytes as well as from string
- use `TryFrom` rather than standalone method for type conversion
> Clean code/no unwrap

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @xJonathanLEI as a contributor

- .all-contributorsrc
- README.md
> :busts_in_silhouette: Add @greged93 as a contributor

- crates/pallets/starknet/src/types.rs
> ⚰️ remove unrelevant todo

- crates/runtime/src/lib.rs
- crates/runtime/src/pallets.rs
> 💡 add comments and rust doc

- Cargo.lock
- crates/node/Cargo.toml
- crates/pallets/starknet/Cargo.toml
- crates/primitives/digest-log/Cargo.toml
- crates/primitives/starknet/Cargo.toml
- crates/runtime/Cargo.toml
> 🔖 prepare `0.1.0-alpha` release

- crates/pallets/starknet/src/tests/call_contract.rs
- crates/pallets/starknet/src/tests/mod.rs
> feat: call_contract tests on erc20

- Cargo.lock
- Cargo.toml
- crates/client/rpc-core/src/lib.rs
- crates/client/rpc/Cargo.toml
- crates/client/rpc/src/lib.rs
- crates/client/rpc/src/madara_backend_client.rs
- crates/node/Cargo.toml
- crates/node/src/rpc/mod.rs
- crates/node/src/rpc/starknet.rs
- crates/node/src/service.rs
- tests/package-lock.json
- tests/tests/test-rpc/test-starknet-rpc.ts
RPC Endpoint that returns an object about the sync status, or false if the node is not syncing.
Creating a new RPC Endpoint.
Issue Number: #205 
This new endpoint looks for `starting_block`, `current_block` and `highest_block`, provided by the `sync_service`. With each block, we get the corresponding Starknet block and return its numbers and hashes respectively.
If the node is not syncing, then it returns false.
> feat: RPC - starknet_syncing

- docs/starknet_features_compatibility.md
> 📝 add `starknet_syncing` in RPC table

- crates/client/rpc-core/Cargo.toml
The command `cargo build --package mc-rpc-core` fails.
Pass
> Add missing 'macro' feature for jsonrpsee

- docs/starknet_features_compatibility.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add `starknet_getClass` in compatibility doc

- docs/starknet_features_compatibility.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add `starknet_getBlockWithTxHashes` in compatibility table

- docs/starknet_features_compatibility.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add `starknet_getClassHashAt` in compatibility table

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @dubzn as a contributor

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @ftupas as a contributor

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @phklive as a contributor

- Cargo.toml
`cargo build -p mp-rpc` does not work
Resolves: #NA
Work
No
> Add missing 'rocksdb' feature for sp-client-db

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/call_contract.rs
- crates/pallets/starknet/src/tests/declare_tx.rs
- crates/pallets/starknet/src/tests/deploy_account_tx.rs
- crates/pallets/starknet/src/tests/erc20.rs
- crates/pallets/starknet/src/tests/invoke_tx.rs
- crates/pallets/starknet/src/tests/l1_message.rs
- crates/primitives/starknet/src/block/serialize.rs
- crates/primitives/starknet/src/crypto/commitment/mod.rs
- crates/primitives/starknet/src/tests/crypto.rs
- crates/primitives/starknet/src/traits/hash.rs
- crates/primitives/starknet/src/transaction/mod.rs
- crates/primitives/starknet/src/transaction/types.rs
- tests/util/starknet.ts
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> Refacto transaction types

- tests/tests/test-starknet/test-starknet-extrinsics.ts
- tests/util/starknet.ts
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> fix: fix deploy test

- crates/client/rpc/src/lib.rs
- crates/pallets/starknet/Cargo.toml
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/declare_tx.rs
- crates/pallets/starknet/src/tests/deploy_account_tx.rs
- crates/pallets/starknet/src/tests/erc20.rs
- crates/pallets/starknet/src/tests/invoke_tx.rs
- crates/pallets/starknet/src/tests/l1_message.rs
- crates/pallets/starknet/src/tests/mock.rs
Some minor inconsistencies that made the file harder to read (hex string with or without leading 0x for example).
Resolves: #NA
Standardize and use `H256`
No
There are probably other things to improve but I wanted to keep this kind of PR small.
> Minor refacto to starknet-pallet test

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @dpinones as a contributor

- docs/starknet_features_compatibility.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 update rpc compatibility table

- docs/contributor-starter-pack.md
Adds a contributor starter pack to guide new contributors.
@abdelhamidbakhta I don't know if I have to push this here or in the documentation repository. Let me know I'll close/change the PR as needed. Is there sufficient information, or do we need some other stuff here?
@phklive if you have the links to some videos and slides you have done for Madara, let's add them. :)
> docs: add contributor starter pack

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @marioiordanov as a contributor

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/declare_tx.rs
- crates/pallets/starknet/src/tests/deploy_account_tx.rs
- crates/pallets/starknet/src/tests/invoke_tx.rs
- crates/primitives/starknet/src/transaction/mod.rs
This reverts commit 527362f4e4897fe85e629f703d551822def2f979.
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> Revert "Execute __validate__ entry point before accepting a transaction (#394)"

- docs/starknet_features_compatibility.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add `starknet_addDeployAccountTransaction` in compatibility table

- tests/tests/test-rpc/test-starknet-rpc.ts
This small PR unskips some tests linked to invoke transactions and deploy account transaction tests (which are now passing with PR #400 merged).
3 tests are skipped
Resolves: #NA
- Add invoke/account deploy transaction testing is unskipped and passing
No
> test: add invoke/deploy account transaction

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @dbejarano820 as a contributor

- .github/workflows/test.yml
Use the self hosted runners to build the `test.yml` ci actions. 
- Bugfix
- Feature
- Build-related changes [x]
- Testing
Use github `ubuntu-latest` image to build and test 
Resolves: #273 
- dedicated github runner host w/ 3 runners for parallel building.
- checkout action changed to `clean: false` to persist build artifacts
- all tooling setup done on the host itself
No
> dev: self hosted runner

- .github/workflows/test.yml
build release integration tests
- Bugfix
- Feature
- Build-related changes [x]
- Testing
integration test ci build debug but tests rely on release
Resolves: HOTFIX
> hotfix: build release integration tests

- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 Add doc badges

- docs/contributor-starter-pack.md
The `contributor-starter-pack.md` documentation is of great importance when onboarding new builders,  it has been a great tool for me. I believe we should take care of it and improve it because of this.
Here are some improvements that came up to me when using it.
Fixed some typos, rephrased some parts of the documentation and added new content where relevant.
No
> Chore: contributor starter pack improvements

- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add rust doc link badge

- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add social badges

- README.md
- 📝 fix badge links
- 📝 fix badge links
- 📝 fix badge links
- 📝 fix badge links
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> fix badge links

- crates/client/storage/src/overrides/schema_v1_override.rs
- tests/tests/test-rpc/test-starknet-rpc.ts
Fixes the failing tests which were linked to incorrect storage key being build.
- Bugfix
4 tests which had links with `get_class_hash_at` were failing due to improper storage key construction.
- Update storage key construction
> fix: encode storage key

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @robinstraub as a contributor

- crates/node/src/chain_spec.rs
- tests/tests/test-rpc/test-starknet-rpc.ts
This PR aims to fix the failing CI integration testing.
- Bugfix
CI integration testing fails in a non-deterministic way.
Resolves: #428 
CI passes every run.
- Update the integration tests to remove inner describe.
- Fix missing argent signer in chain_specs.
> fix: flaky CI test

- crates/client/rpc-core/src/lib.rs
- crates/client/rpc/src/lib.rs
- crates/client/storage/src/overrides/mod.rs
- crates/client/storage/src/overrides/schema_v1_override.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/runtime_api.rs
- crates/primitives/starknet/src/storage/mod.rs
- crates/runtime/src/lib.rs
- examples/rpc/starknet/starknet_getNonce.hurl
- tests/tests/test-rpc/test-starknet-rpc.ts
- tests/util/utils.ts
Implements the starknet_getNonce transaction endpoint.
- Feature
- Testing
starknet_getNonce missing from the rpc endpoints.
Resolves: #207
starknet_getNonce available.
- Adds starknet_getNonce to the rpc endpoints
- Add nonce to the runtime api and storage override
- Test getNonce
This PR is based off of @phklive's work (PR #390).
> feat: get nonce

- .github/workflows/benchmark.yml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> Ci remove download old bench report

- .github/workflows/docker.yml
Use updated actions to remove ci warnings and future deprecation
- Bugfix
- Feature
- Build-related changes [x]
- Testing
[warnings bottom](https://github.com/keep-starknet-strange/madara/actions/runs/5022484807)
Resolves: #NA
- [beerus test w/ new actions](https://github.com/keep-starknet-strange/beerus/actions/runs/5073100833)
- 
No
> dev: remove ci warnings 

- Cargo.lock
- Cargo.toml
- crates/client/rpc-core/Cargo.toml
- crates/client/rpc-core/src/lib.rs
- crates/client/rpc-core/src/tests.rs
- crates/client/rpc-core/src/utils.rs
- crates/client/rpc/Cargo.toml
- crates/client/rpc/src/lib.rs
- crates/primitives/starknet/Cargo.toml
- crates/primitives/starknet/src/transaction/types.rs
Changes to track the current lastest commit on the `dev/jsonrpc_0_3_0` branch on `starknet-rs`.
- Other (please describe): dependency update
Using an orphaned commit in `starknet-rs`.
Uses the latest commit on the `dev/jsonrpc_0_3_0` branch.
No
N/A
> feat: update `starknet-rs` and resolve changes

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @edisontim as a contributor

- crates/primitives/starknet/src/transaction/mod.rs
The issue #330 was resolved, we should clean up the comments related to it.
- Other (please describe): cleanup
> chore: cleaning up old comment

- .codecov.yml
- .github/workflows/benchmark.yml
- .github/workflows/linters.yml
- .github/workflows/test.yml
Add dedicated runner for deterministic benchmarking
- Bugfix
- Feature
- Testing [x]
Benchmarking is done on shared runner giving uncertain results for the benchmark
Resolves: #NA
- Add dedicated runner for deterministic benchmarking
- Remove node setup in favor of `nvm` on the runner host
- Remove duplicate linter run on `push` and `pr`
- ignore various paths for benchmarking
No
> dev: benchmark runner

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @lana-shanghai as a contributor

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @d-roak as a contributor

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @rkdud007 as a contributor

- .github/workflows/benchmark.yml
- benchmarking/package-lock.json
- tests/tests/constants.ts
- tests/tests/test-rpc/test-starknet-rpc.ts
- Bugfix
The Benchmark Action fails not because of the performance checks but because of a file not found error.
Removed the loading of a file in the shared constant file but put it right in the test.
No
The typescript part of the project could be refactored in a monorepo fashion.
> Fix CI benchmark

- .github/workflows/benchmark.yml
- benchmarking/scripts/metrics.js
Use a python script to compare previous and current metrics result.
Resolves: #488
Use the [Continuous Benchmark action](https://github.com/marketplace/actions/continuous-benchmark) to keep track of the metrics.
No
> Use GH action to track benchmark erf

- .github/workflows/benchmark.yml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> No commit comment for benchmark CI

- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add benchmark badge and explainer

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @apoorveth as a contributor

- dev/bench/index.html
- Bugfix
The benchmark dashboard displays duplicated data
Dups are removed (based on commit hash)
No
> Filter out dup in data file

- README.md
- docs/madara-coding-principles.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 add coding principles

- .devcontainer/devcontainer.json
- docs/madara-coding-principles.md
The devcontainer config doesn't work as is because of missing `protoc`.
Works out of the box
No
Also added some minimal spec requirements
> [devcontainer] Fix missing protoc

- infra/docker/Dockerfile
> Embed chain specs in docker

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @fracek as a contributor

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @ptisserand as a contributor

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/declare_tx.rs
- crates/pallets/starknet/src/tests/deploy_account_tx.rs
- crates/pallets/starknet/src/tests/invoke_tx.rs
- crates/pallets/starknet/src/tests/l1_message.rs
- crates/pallets/starknet/src/tests/mock.rs
- crates/runtime/src/pallets.rs
- Feature
Resolves: #539 
- Add `TransactionLongevity` to the pallet config so it can be configurable
- Set the longevity value in runtime
- Add tests for transaction longevity
No
> feat: configure transaction longevity

- infra/starknet-stack/docker-compose.yml
Added a faucet to the starknet-stack
- Feature
No
> infra: add a faucet

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @zizou0x as a contributor

- Cargo.lock
- Cargo.toml
- crates/node/src/benchmarking.rs
- crates/node/src/chain_spec.rs
- crates/node/src/command.rs
- crates/runtime/Cargo.toml
- crates/runtime/src/config.rs
- crates/runtime/src/lib.rs
- crates/runtime/src/opaque.rs
- crates/runtime/src/pallets.rs
- crates/runtime/src/runtime_tests.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 🔥 remove `pallet_balances`

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @MdTeach as a contributor

- benchmarking/package.json
- benchmarking/scripts/cairo-execution.yml
- benchmarking/scripts/cairo-storage.yml
- benchmarking/scripts/chain.yml
- benchmarking/scripts/starknet-erc20.yml
- scripts/run_node.sh
- Other (please describe): CI
Resolves: #569 
- add a argument to `run_node.sh` script which is the log level to be used. by default its info.
- remove log lines from CI run
- run madara which log level `error` in CI runs
No
> fix(CI): Dont log messages to stdout & use madara with log level error

- cairo-contracts/build/UniversalDeployer.json
- cairo-contracts/src/UniversalDeployer.cairo
- crates/node/src/chain_spec.rs
- crates/node/src/constants.rs
- tests/grep
- tests/tests/constants.ts
- tests/tests/test-rpc/test-starknet-rpc.ts
- tests/tests/test-starknet/test-starknet-extrinsics.ts
- tests/util/starknet.ts
- Feature
The current genesis state of Madara lacks [UDC](https://docs.openzeppelin.com/contracts-cairo/0.6.1/udc), which is now the recommended method of deploying contracts.
Resolves: #530 
The PR adds UDC as part of the genesis state of the contract.
No
The contract has been deployed to the same address as other deployments of starknet, i.e at **0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf** to make sure compatibility with existing tooling.
> feat: add UDC to the genesis state 🥷

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @kariy as a contributor

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @lambda-0x as a contributor

- infra/kustomize/gke/deployment.yaml
- infra/kustomize/gke/kustomization.yaml
- infra/kustomize/gke/network.yaml
- infra/kustomize/gke/service.yaml
I dont have time to parameterize everything nicely but hopefully a decent starting point for others
> GKE Kustomize / ConfigConnector manifests

- crates/primitives/starknet/src/block/header.rs
Fixes block hash computation according to [starknet docs](https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/header/#block_hash)
> fix: block hash

- crates/primitives/starknet/src/block/header.rs
This reverts commit 4a9bc0a008428c594388a375fc3be367940ef165.
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> Revert "fix: block hash (#634)"

- crates/client/rpc-core/src/utils.rs
Resolves: #625 
No 
Much of this was already simplified after #552 refactor, so this is the only thing i could think of to simplify.
> chore: remove duplication

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @exp-table as a contributor

- crates/client/rpc-core/src/utils.rs
- crates/client/rpc/src/lib.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/declare_tx.rs
- crates/pallets/starknet/src/tests/deploy_account_tx.rs
- crates/pallets/starknet/src/tests/erc20.rs
- crates/pallets/starknet/src/tests/invoke_tx.rs
- crates/pallets/starknet/src/tests/mock.rs
- crates/primitives/starknet/src/crypto/commitment/mod.rs
- crates/primitives/starknet/src/tests/crypto.rs
- crates/primitives/starknet/src/transaction/types.rs
- crates/runtime/src/lib.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> ⚡️ remove unnecessary conversion between `chain_id` string representation and felt wrapper

- crates/primitives/starknet/src/execution/call_entrypoint_wrapper.rs
- crates/primitives/starknet/src/tests/transaction.rs
- crates/primitives/starknet/src/transaction/types.rs
- Testing
Resolves: #627 
No
- added tests but cannot yet run all, because bounded types are very large and when trying to run them allocation for that large chunk fails
- ref: #250
> dev(test): add tests for TryFrom implementation for DeployAccountTransaction

- Cargo.lock
- Cargo.toml
- crates/node/src/chain_spec.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/current_block.rs
- crates/pallets/starknet/src/tests/mock.rs
- crates/runtime/Cargo.toml
- crates/runtime/src/config.rs
- crates/runtime/src/lib.rs
- crates/runtime/src/pallets.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 🗑️ YAGNI for the win (remove `pallet_sudo` and 2 extrinsics)

- crates/pallets/starknet/src/blockifier_state_adapter.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/types.rs
Switch `Nonce` type from `U256` to `Felt252Wrapper` to comply with the specs.
> feat: nonce type 🔨

- crates/primitives/starknet/src/tests/transaction.rs
* Testing
Resolves: #626 
At `primitives/starknet/src/transation/types.rs`  added unit tests for the `impl TryFrom<BroadcastedInvokeTransaction> for InvokeTransaction` 
No
No
> dev(test): add tests for TryFrom implementation for InvokeTransaction from BroadcastedInvokeTransaction

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/mock.rs
- crates/runtime/src/pallets.rs
- crates/runtime/src/types.rs
Currently the steps are hardcoded into `get_block_context`.
Resolves: #545 
The steps are configurable now in `runtime/pallets.rs`
No.
> chore: configurable max steps

- Cargo.lock
- Cargo.toml
- crates/client/block-proposer/src/lib.rs
- crates/node/Cargo.toml
- crates/node/src/chain_spec.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> ⬆️ latest substrate version + refactor block proposer

- crates/client/rpc/src/lib.rs
DRYing some code in the client rpc for cleaner code and duplication reduction.
Repetitive code
Resolves: #629 
DRY code
No
> refacto: DRY functions in starknet rpc api server

- .github/workflows/docker.yml
Drop arm64 support for beta release
- Bugfix
> fix: drop arm64 support for beta release

- infra/docker/Dockerfile
> fix: add codebase to docker image

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/mock.rs
- crates/pallets/starknet/src/tests/sequencer_address.rs
Resolves: #716 
Not sure if this counts as breaking change.
> dev: use Felt252Wrapper instead of [u8; 32]

- crates/client/rpc-core/src/utils.rs
- crates/node/src/chain_spec.rs
- crates/pallets/starknet/src/blockifier_state_adapter.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/message.rs
- crates/pallets/starknet/src/tests/utils.rs
- crates/primitives/starknet/src/execution/contract_class_wrapper.rs
- crates/primitives/starknet/src/starknet_serde/mod.rs
- crates/primitives/starknet/src/state/mod.rs
- crates/primitives/starknet/src/tests/utils.rs
- crates/primitives/starknet/src/transaction/mod.rs
- crates/primitives/starknet/src/transaction/types.rs
- crates/runtime/src/lib.rs
Link the FIXMEs in the code to issues created.
FIXMEs are not linked to issues.
Resolves: #NA
FIXMEs are linked to issues.
No
> fix: link FIXMEs with issues

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @Pilouche as a contributor

- crates/node/src/cli.rs
- crates/node/src/command.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 🚨 cargo clippy

- crates/client/block-proposer/src/lib.rs
Reverts keep-starknet-strange/madara#739
> Revert "Fix: set finalization time back to 33%"

- crates/primitives/starknet/src/execution/entrypoint_wrapper.rs
- crates/primitives/starknet/src/execution/mod.rs
- crates/primitives/starknet/src/sequencer_address/mod.rs
- crates/primitives/starknet/src/transaction/types.rs
- crates/primitives/starknet/src/transaction/utils.rs
> dev: clean up the numerous #[cfg(feature=std)] flags

- crates/primitives/starknet/src/tests/transaction.rs
- crates/primitives/starknet/src/transaction/mod.rs
- updated.md
Resolves: #745 
Maybe
List of duplicate functions i found (lmk if there are any other):
- verify_tx_version (updated function + test)
- handle_nonce (updated function + calls)
- validate_tx (updated function + no change in behaviour)
- validate_entrypoint_calldata (is same)
- validate_entry_point_selector (is same)
> dev: fix compatibility with blockifier

- .github/workflows/docker.yml
- re-add arm64 support
- separate amd64 from arm64
we can refactor this after https://github.com/actions/runner-images/issues/5631
> feat: build arm64 image in ci

- docs/contributor-starter-pack.md
> doc: suggest opening draft PR

- Cargo.lock
- Cargo.toml
- crates/client/block-proposer/Cargo.toml
- crates/client/block-proposer/src/lib.rs
- Testing
Resolves: #703 
Implements unit tests for the block proposer logic
No
No
> test: add tests for Block proposer logic

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/tests/mock/default_mock.rs
- crates/pallets/starknet/src/tests/mock/state_root_mock.rs
- crates/primitives/starknet/src/block/header.rs
- crates/primitives/starknet/src/tests/block.rs
- crates/runtime/src/pallets.rs
> dev: change protocol_version to be u8 and make it configurable in pallet

- Cargo.lock
- crates/node/Cargo.toml
- crates/node/src/genesis_block.rs
- crates/node/src/main.rs
- crates/node/src/service.rs
- Feature
Replace `new_full_parts` with `new_full_parts_with_genesis_build`, implement GenesisBlockBuilder, add Starknet block to genesis block header digest 
Resolves: [issue](https://github.com/keep-starknet-strange/madara/issues/754)
> Add GenesisBlockBuilder to new_full_parts

- docs/sharingan-starter-pack.md
Few modifications on the starter pack for Sharingan:
1. Add telemetry url and command line option.
2. Update docker volume.
3. Update URLs to the new `madara.zone` domain.
> docs: sharingan guide update

- .github/workflows/benchmark.yml
- benchmarking/package.json
- benchmarking/scripts/combine-metrics-state-root.js
- crates/node/Cargo.toml
- crates/runtime/Cargo.toml
- crates/runtime/src/pallets.rs
- scripts/run_node.sh
> dev: add feature flag to enable state root

- dev/bench-with-state-root/index.html
- dev/bench/index.html
- Feature
Resolves: #800
- benchmark page has navigation bar
No
> dev: add nav bar between different benchmark page

- .github/workflows/docker.yml
> fix: docker ci build

- tests/tests/constants.ts
- tests/tests/test-rpc/test-starknet-rpc.ts
- Feature
- Added a test case for Cairo 1 account deployment
No
> Deploy account test for Cairo 1

- crates/pallets/starknet/src/lib.rs
- Bugfix
Fix estimate fee
Resolves: #NA
Estimate fee works for declare, deploy account and invoke.
No
> fix estimate fee

- crates/client/rpc/src/lib.rs
- Bugfix
Requesting the state update for the genesis block returns a `Block not found` error.
The state update for the genesis block is returned.
No
> Handle starknet_getStateUpdate for genesis block

- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 📝 rework a bit the readme

- .gitmodules
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 🧱 add peripheral repos as submodules

- crates/pallets/starknet/src/lib.rs
- scripts/fund.sh
Add a script to fund an account for a certain amount. Also adds some needed logging for pool validation failure.
- Feature
No script for funding and no pool validation error logging.
Resolves: #NA
- Fund.sh script to fund account for amount
- Pool validation error logging
No
> fund script + pool validation error

- .prettierignore
- benchmarking/scripts/combine-metrics-state-root.js
- benchmarking/scripts/final-check.js
- benchmarking/scripts/functions.js
- benchmarking/scripts/metrics.js
- docs/faucet-setup.md
- tests/tests/constants.ts
- tests/tests/test-starknet-rpc/test-block.ts
- tests/tests/test-starknet-rpc/test-cairo-1.ts
- tests/tests/test-starknet-rpc/test-contracts.ts
- tests/tests/test-starknet-rpc/test-events.ts
- tests/tests/test-starknet-rpc/test-state-root.ts
- tests/tests/test-starknet-rpc/test-state-update.ts
- tests/tests/test-starknet-rpc/test-storage.ts
- tests/tests/test-starknet-rpc/test-transactions.ts
- tests/tests/test-starknet/test-starknet-extrinsics.ts
- tests/util/block.ts
- tests/util/dev-node.ts
- tests/util/expect.ts
- tests/util/setup-dev-tests.ts
- tests/util/starknet.ts
- tests/util/substrate-rpc.ts
- tests/util/utils.ts
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 🚨 prettier

- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> 🫶 add LambdaClass Madara Explorer reference

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @hel-kame as a contributor

- crates/pallets/starknet/src/tests/block.rs
- crates/pallets/starknet/src/tests/mod.rs
- Testing
Resolves: #639
- added unit tests for block functions in Starknet pallet
No
> added store_block and get_block_context unit tests

- README.md
Fixed docs github link in readme
> typo fix :D

- Cargo.lock
- crates/primitives/starknet/Cargo.toml
This reverts commit f25f399d39ffb181c8d75c528c3aded83ec17152.
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> Revert "build(deps): bump zstd from 0.12.3+zstd.1.5.2 to 0.12.4 (#886)"

- README.md
`prettier` doesn't manage to check the main `README.md` file
Not sure why though.
Removing the `prettier-ignore` made the trick, not sure why though!
No
> Fix prettier not linting README

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @clexmond as a contributor

- .all-contributorsrc
- README.md
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> :busts_in_silhouette: Add @Tidus91 as a contributor

- docs/content/articles/en/madara-beast-article.md
fixed Create madara beast article.md
See #932
was not allowed to push
> Create madara beast article.md #932

- Cargo.lock
- Cargo.toml
- starknet-rpc-test/Cargo.toml
- starknet-rpc-test/get_block_hash_and_number.rs
- starknet-rpc-test/get_block_number.rs
- starknet-rpc-test/src/lib.rs
- Bugfix
- Feature
X Refactoring (no functional changes, no API changes)
- Testing
Resolves: #NA
-Uses `starknet-rs` to query starknet rpc from madara node
Yes
> ♻️ refractor e2e tests starknet-rs

- CHANGELOG.md
- starknet-rpc-test/Cargo.toml
- starknet-rpc-test/chain_id.rs
- starknet-rpc-test/src/constants.rs
- starknet-rpc-test/src/lib.rs
- starknet-rpc-test/src/utils.rs
- Bugfix
X Feature
X Testing
Resolves: #NA
- Adds `starknet_chainId` rpc test
> ✅ chain_id

- Cargo.lock
- Cargo.toml
- crates/client/block-proposer/Cargo.toml
- crates/client/db/Cargo.toml
- crates/client/mapping-sync/Cargo.toml
- crates/client/rpc-core/Cargo.toml
- crates/client/rpc/Cargo.toml
- crates/client/storage/Cargo.toml
- crates/node/Cargo.toml
- crates/pallets/starknet/Cargo.toml
- crates/primitives/digest-log/Cargo.toml
- crates/primitives/starknet/Cargo.toml
- crates/runtime/Cargo.toml
change version number in `Cargo.toml. files
> release: v0.1.0

- .all-contributorsrc
- CHANGELOG.md
- README.md
- tests/tests/test-starknet-rpc/test-block.ts
Add new contributor, commits [here](https://github.com/keep-starknet-strange/madara/commits?author=0xAsten)
> :busts_in_silhouette: Add @0xAsten and @ben2077 as a contributor

- Cargo.lock
- crates/pallets/starknet/Cargo.toml
Changelog ignored because the previous entry #1009
> ci: fixing madara bin for aarch64 linux

- .github/workflows/changelog.yml
- CHANGELOG.md
- Other (please describe): CI
Resolves: #1008 
Changelog is not enforced on PR with tags `Skip-Changelog` (default tag) and `dependencies`
No
> chore(CI): add `dependencies` tag to changelog ignore list

- CHANGELOG.md
- README.md
Added app chain template in the readme
> feat: app chain template readme

- CHANGELOG.md
- Cargo.lock
- crates/primitives/starknet/Cargo.toml
- crates/primitives/starknet/src/fees/mod.rs
Performance improvement in `calculate_l1_gas_by_vm_usage`
Using inefficient data structures 
Resolves: #1116 
Integrated PHF and eliminated the need to allocate extra memory for new data structures
No
> perf: use perfect hash function in calculate_l1_gas_by_vm_usage

- .vscode/settings.json
- CHANGELOG.md
- crates/pallets/starknet/Cargo.toml
- Bugfix
Currently rpc tests fail due to compilation error when you try to run cargo test inside crates/client/rpc.
Resolves: #1098 
Fixing the compiling issue by adding mp-sequencer-address inside crate std feature
Tests are 
- Navigate inside `crates/client/rpc`
- run `cargo test`
No
> fix: add mp-sequencer-address in pallet crate

- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/transaction_validation.rs
- crates/primitives/transactions/src/execution.rs
- crates/primitives/transactions/src/lib.rs
> Validate L1 Messages

- CHANGELOG.md
- README.md
- crates/primitives/transactions/src/compute_hash.rs
- fix: fixed declare V0 placeholder with the hash of an empty list of felts
> fixed declareV0

- crates/client/data-availability/src/lib.rs
- crates/client/transaction-pool/README.md
fix typos in docs and comments.
> chore: fix typos

- README.md
Bugfix
Wrong link
Correct link
-
-
-
No
> fixed "Madara Docsite" link

- CHANGELOG.md
- Cargo.toml
Resolves: #NA
Compile the code in dev profile with incremental compiling, saving compilation info to the disk which allows for faster compilation time.
> dev: incremental compiling

- CHANGELOG.md
- docs/content/articles/es/madara-beast-article.md
> Translation of madara-beast-article to Spanish

- starknet-rpc-test/call.rs
Fixes rpc-tests broken by adding fee token's name to genesis.
see [here](https://github.com/keep-starknet-strange/madara/actions/runs/6783313488/job/18437475096)
> 🐛 fix rpc test

- Cargo.lock
- docs/rpc-contribution.md
Documentation content changes
I fixed some typos in docs/rpc-contribution.md.
Hope it will help.
Thanks
fishseabowl
> fix: Text improvements in rpc-contribution.md

- CHANGELOG.md
- Cargo.lock
- crates/client/data-availability/Cargo.toml
- crates/client/data-availability/src/celestia/mod.rs
Updated the celestia dependency to the new package.
> Celestia bump

- CHANGELOG.md
- crates/client/data-availability/Cargo.toml
- crates/client/data-availability/src/lib.rs
- crates/node/src/service.rs
- da-test/src/utils.rs
- Feature
Currently, every build of Madara includes the Avail and Celestia libraries, as mention in issue #1353 
Move the Avail and Celestia libraries behind feature flags
> Add avail and celestia crates behind feature flags #1353

- .github/workflows/configs-verifier.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- configs/index.json
- crates/node/Cargo.toml
- crates/node/src/commands/setup.rs
- crates/node/src/configs.rs
- Feature
As mentioned in issue #1348, the use of the MD5 hash function does not guarantee security.
Resolves: #1348
After discussion, replacing the MD5 hash function with the more secure SHA-3-256 hash function.
> Replace md5 with sha_256 hash function #1348

- CHANGELOG.md
- crates/node/src/commands/run.rs
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> fix(cli): repair broken cli for da conf

- CHANGELOG.md
- crates/client/data-availability/src/avail/config.rs
- crates/client/data-availability/src/celestia/config.rs
- crates/client/data-availability/src/ethereum/config.rs
- crates/node/src/commands/run.rs
- crates/node/src/service.rs
- da-test/src/utils.rs
> refacto: remove abusive  impl

- CHANGELOG.md
- Cargo.toml
- Bugfix
- Feature
- Testing
Resolves: #NA
-
-
-
> release v0.7.0

- CHANGELOG.md
- Cargo.lock
- crates/client/db/src/da_db.rs
- crates/client/db/src/l1_handler_tx_fee.rs
- crates/client/db/src/lib.rs
- crates/client/db/src/mapping_db.rs
- crates/client/db/src/messaging_db.rs
- crates/client/db/src/sierra_classes_db.rs
- crates/client/mapping-sync/src/sync_blocks.rs
- crates/client/rpc-core/src/lib.rs
- crates/client/rpc/src/lib.rs
- crates/client/rpc/src/madara_backend_client.rs
- crates/client/rpc/src/trace_api.rs
- crates/pallets/starknet/runtime_api/src/lib.rs
- crates/pallets/starknet/src/lib.rs
- crates/pallets/starknet/src/simulations.rs
- crates/pallets/starknet/src/tests/invoke_tx.rs
- crates/pallets/starknet/src/tests/l1_handler_validation.rs
- crates/pallets/starknet/src/tests/mod.rs
- crates/pallets/starknet/src/tests/re_execute_transactions.rs
- crates/pallets/starknet/src/transaction_validation.rs
- crates/primitives/simulations/Cargo.toml
- crates/primitives/transactions/src/compute_hash.rs
- crates/primitives/transactions/src/getters.rs
- crates/primitives/transactions/src/lib.rs
- crates/primitives/transactions/src/utils.rs
- crates/runtime/src/lib.rs
- starknet-rpc-test/Cargo.toml
- starknet-rpc-test/src/constants.rs
- starknet-rpc-test/trace_block.rs
Add `traceBlockTransactions` rpc 
supersed #1411
> feat: add rpc traceBlock

- CHANGELOG.md
- crates/client/rpc/src/trace_api.rs
Clean trace API
- 
Code is messy.
Resolves: #NA
Code is clean.
No
> clean trace api

- .github/workflows/starknet-e2e-tests.yml
- CHANGELOG.md
- crates/client/settlement/src/sync_state.rs
- crates/primitives/transactions/src/execution.rs
> Refactoring : Removed Redundant logs in madara

- crates/primitives/snos-output/src/codec.rs
Resolves: #NA
fix some typos in comments
> chore: fix some typos in comments

- .gitmodules
- CHANGELOG.md
Git submodules deleted
Refactor
- Bugfix
- Feature
- Testing
Resolves: #1596 
- Git submodules are deleted.
> Rm submodules

- crates/client/storage/src/lib.rs
- crates/pallets/starknet/src/lib.rs
Resolves: #NA
remove duplicate words
No
> chore: remove duplicate words

- CHANGELOG.md
- crates/client/l1-gas-price/src/types.rs
- crates/client/l1-gas-price/src/worker.rs
- crates/node/src/service.rs
- docs/content/articles/cn/madara-beast-article.md
- docs/contributor-starter-pack.md
- examples/messaging/eth-config.json
- Bugfix
- Feature
Buggy l1 gas price fetching code.
Resolves: #1618 
Added feature flag support for fetching of l1 gas prices if fee is not disabled and added few other small fixes.
No
> feat: L1 gas price/fix
